server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: postgres
    password: themassacre
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true